import 'server-only';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@mabru/ui";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

// The RootLayout is now an async Server Component
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): Promise<JSX.Element> {
  // Read environment variables on the server
  const config = {
    authority: process.env.NEXT_PUBLIC_OIDC_AUTHORITY,
    client_id: process.env.NEXT_PUBLIC_OIDC_CLIENT_ID,
    redirect_uri: process.env.NEXT_PUBLIC_OIDC_REDIRECT_URI,
    post_logout_redirect_uri: process.env.NEXT_PUBLIC_OIDC_POST_LOGOUT_REDIRECT_URI,
    silent_redirect_uri: process.env.NEXT_PUBLIC_OIDC_SILENT_REDIRECT_URI,
    scope: process.env.NEXT_PUBLIC_OIDC_SCOPE,
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider config={config}>{children}</AuthProvider>
      </body>
    </html>
  );
}
