version: v2.2.0

serve:
  cookies:
    same_site_mode: "Lax"
  public:
    cors:
      enabled: true
      allowed_origins:
        - ${CORS_ALLOWED_ORIGINS}
  admin:
    cors:
      enabled: true
      allowed_origins:
        - ${CORS_ALLOWED_ORIGINS}

dsn: "postgres://ory:ory@postgres:5432/hydra?sslmode=disable&search_path=public"

secrets:
  system:
    - ${HYDRA_SECRETS_SYSTEM}

urls:
  self:
    issuer: ${HYDRA_PUBLIC_URL}
  
  login: ${KRATOS_BROWSER_URL}/self-service/login/browser
  consent: ${AUTH_APP_URL}/consent
  logout: ${AUTH_APP_URL}/logout
  error: ${AUTH_APP_URL}/error

oidc:
  subject_identifiers:
    supported_types:
      - public

log:
  level: debug
  format: text
