version: v0.13.0

serve:
  public:
    base_url: ${KRATOS_PUBLIC_URL}
    cors:
      enabled: true
      allowed_origins:
        - ${CORS_ALLOWED_ORIGINS}
  admin:
    base_url: http://kratos:4434

secrets:
  cookie:
    - ${KRATOS_SECRETS_COOKIE}

selfservice:
  default_browser_return_url: ${DEFAULT_BROWSER_RETURN_URL}
  
  methods:
    password:
      enabled: false
    oidc:
      enabled: true
      config:
        providers:
          - id: google
            provider: google
            client_id: 219976165015-4ere2bv60g1f0ijb0g2g4ik42b716kem.apps.googleusercontent.com
            client_secret: ${KRATOS_OIDC_GOOGLE_CLIENT_SECRET}
            scope: [email, profile]
            mapper_url: file:///etc/kratos/google.jsonnet

  flows:
    error:
      ui_url: ${AUTH_APP_URL}/error
    login:
      ui_url: ${AUTH_APP_URL}/login
    logout:
      after:
        default_browser_return_url: ${AUTH_APP_URL}/logout
    registration:
      ui_url: ${AUTH_APP_URL}/registration
      after:
        oidc:
          hooks:
            - hook: web_hook
              config:
                url: ${AUTH_APP_URL}/api/hooks/registration-after/
                method: POST
                body: base64://ZnVuY3Rpb24oY3R4KSBjdHguaWRlbnRpdHk=
                can_interrupt: true
            - hook: session

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/kratos/identity.schema.json

oauth2_provider:
  url: ${HYDRA_ADMIN_URL}

log:
  level: debug
  format: text

session:
  cookie:
    same_site: "Lax"
    domain: "localhost"