name: Build, Push, and Deploy

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: brunomarchasson

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        app: [auth, hub, resume]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store # This is pnpm's global content-addressable store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.app }} image
        run: |
          echo "Building and pushing ${{ matrix.app }} image..."
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/mabru-${{ matrix.app }}:latest -f apps/${{ matrix.app }}/Dockerfile .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/mabru-${{ matrix.app }}:latest
          
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - name: Deploy auth app
        run: curl -X POST ${{ secrets.DOKPLOY_AUTH_WEBHOOK }}

      - name: Deploy hub app
        run: curl -X POST ${{ secrets.DOKPLOY_HUB_WEBHOOK }}

      - name: Deploy resume app
        run: curl -X POST ${{ secrets.DOKPLOY_RESUME_WEBHOOK }}
