name: Build, Push, and Deploy

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: brunomarchasson

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        # Define the apps to build in parallel
        app: [auth, hub, resume]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.app }} image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/${{ matrix.app }}/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/mabru-${{ matrix.app }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/mabru-${{ matrix.app }}:${{ github.sha }}
          build-args: |
            NEXT_PUBLIC_OIDC_AUTHORITY=https://dummy.com
            NEXT_PUBLIC_OIDC_CLIENT_ID=dummy
            NEXT_PUBLIC_OIDC_REDIRECT_URI=https://dummy.com/callback
            NEXT_PUBLIC_OIDC_POST_LOGOUT_REDIRECT_URI=https://dummy.com/logout
            NEXT_PUBLIC_OIDC_SILENT_REDIRECT_URI=https://dummy.com/silent-renew

  deploy:
    runs-on: ubuntu-latest
    # This job depends on the successful completion of all matrix jobs in 'build'
    needs: build

    steps:
      - name: Deploy auth app
        run: curl -X POST ${{ secrets.DOKPLOY_AUTH_WEBHOOK }}

      - name: Deploy hub app
        run: curl -X POST ${{ secrets.DOKPLOY_HUB_WEBHOOK }}

      - name: Deploy resume app
        run: curl -X POST ${{ secrets.DOKPLOY_RESUME_WEBHOOK }}