name: Build, Push, and Deploy

# This workflow runs on every push to the 'master' branch
on:
  push:
    branches:
      - master

# Environment variables available to all jobs
env:
  # The GitHub Container Registry to push to
  REGISTRY: ghcr.io
  # The GitHub username or organization name that owns the repository
  IMAGE_OWNER: brunomarchasson

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Permissions needed by the workflow to push to GitHub Container Registry
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # === Build and Push Section ===

      - name: Build and push auth image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/auth/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/mabru-auth:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/mabru-auth:${{ github.sha }}

      - name: Build and push hub image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/hub/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/mabru-hub:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/mabru-hub:${{ github.sha }}

      - name: Build and push resume image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/resume/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/mabru-resume:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/mabru-resume:${{ github.sha }}

      # === Trigger Deployments Section ===

      - name: Deploy auth app
        if: success()
        run: curl -X POST ${{ secrets.DOKPLOY_AUTH_WEBHOOK }}

      - name: Deploy hub app
        if: success()
        run: curl -X POST ${{ secrets.DOKPLOY_HUB_WEBHOOK }}

      - name: Deploy resume app
        if: success()
        run: curl -X POST ${{ secrets.DOKPLOY_RESUME_WEBHOOK }}
